- name: Generate Kubernetes join command
  command: >
    sudo kubeadm token create --print-join-command
  register: kubeadm_token_output

- name: Save join command to a file
  copy:
    content: "{{ kubeadm_token_output.stdout }}"
    dest: /tmp/kubeadm_join_command.sh
