variable "vpc_cidr" {}
variable "public_subnet_cidr" {}
variable "private_subnet_cidr" {}
variable "ami_id" {}
variable "bastion_instance_type" {}
variable "ec2_instance_type" {}
variable "key_name" {}
variable "my_ip" {}
variable "aws_region" {}