---
- name: Configure Kubernetes Master Node
  hosts: master
  become: yes
  tasks:
    - name: Configure Kubernetes on Master nodes
      include_role:
        name: cluster_init

- name: Configure Kubernetes Worker Nodes
  hosts: worker
  become: yes
  tasks:
    - name: Configure Kubernetes on Worker nodes
      include_role:
        name: cluster_init
